import { writeFileSync } from 'node:fs';
import { lessonSchema } from '../src/lib/lesson';
import { topologicalOrder, type Roadmap } from '../src/lib/roadmap';
import { readRoadmap, readLessonFiles, type LessonFile } from './lib/content-io';

export function renderCurriculum(roadmap: Roadmap, lessons: LessonFile[]): string {
  const bySlug = new Map(lessons.map((l) => [l.slug, l]));
  const ordered = topologicalOrder(roadmap.nodes);

  const totalMinutes = lessons.reduce((sum, l) => {
    const parsed = lessonSchema.safeParse(l.frontmatter);
    return sum + (parsed.success ? parsed.data.minutes : 0);
  }, 0);

  const lines: string[] = [
    '<!-- Generated by scripts/generate-curriculum.ts — DO NOT EDIT BY HAND. -->',
    '<!-- Run `npm run gen:curriculum` after changing content/roadmap.json. -->',
    '',
    '# Curriculum',
    '',
    `**${lessons.length} lessons** · roughly ${Math.round(totalMinutes / 60)} hours of reading ·`,
    'free and open source.',
    '',
    'Work top to bottom. Each lesson lists what it assumes you already know, so if',
    'you already have some of this, skip ahead — the prerequisites tell you whether',
    'you are ready.',
    '',
  ];

  for (const stage of roadmap.stages) {
    const stageNodes = ordered.filter((n) => n.stage === stage.id);
    if (stageNodes.length === 0) continue;

    lines.push(`## Stage ${stage.id} · ${stage.name}`, '');
    lines.push('| # | Lesson | Time | Level | What it covers |');
    lines.push('|---|---|---|---|---|');

    for (const node of stageNodes) {
      const lesson = bySlug.get(node.id);
      if (!lesson) continue;
      const parsed = lessonSchema.safeParse(lesson.frontmatter);
      if (!parsed.success) continue;
      const { title, minutes, difficulty, summary, order } = parsed.data;
      lines.push(
        `| ${String(order).padStart(2, '0')} | [${title}](${lesson.file}) | ${minutes} min | ${difficulty} | ${summary} |`,
      );
    }
    lines.push('');
  }

  lines.push(
    '---',
    '',
    'Prefer an interactive version with progress tracking and search?',
    'Visit <https://sumitsingh4411.github.io/ai-roadmap>.',
    '',
  );

  return lines.join('\n');
}

function main(): void {
  writeFileSync('CURRICULUM.md', renderCurriculum(readRoadmap(), readLessonFiles()), 'utf8');
  console.log('✓ Wrote CURRICULUM.md');
}

if (import.meta.url === `file://${process.argv[1]}`) main();
