import { writeFileSync } from 'node:fs';
import { lessonSchema } from '../src/lib/lesson';
import { topologicalOrder, type Roadmap } from '../src/lib/roadmap';
import { readRoadmap, readLessonFiles, type LessonFile } from './lib/content-io';

/** "1 lesson" vs "3 lessons" — pluralizes a noun for a given count. */
function pluralize(count: number, singular: string, plural = `${singular}s`): string {
  return count === 1 ? singular : plural;
}

/** Formats a reading-time total as minutes when under an hour, hours otherwise. */
function formatReadingTime(totalMinutes: number): string {
  if (totalMinutes < 60) {
    return `${totalMinutes} ${pluralize(totalMinutes, 'minute')}`;
  }
  const hours = Math.round(totalMinutes / 60);
  return `${hours} ${pluralize(hours, 'hour')}`;
}

export function renderCurriculum(roadmap: Roadmap, lessons: LessonFile[]): string {
  const bySlug = new Map(lessons.map((l) => [l.slug, l]));
  const ordered = topologicalOrder(roadmap.nodes);

  const totalMinutes = lessons.reduce((sum, l) => {
    const parsed = lessonSchema.safeParse(l.frontmatter);
    return sum + (parsed.success ? parsed.data.minutes : 0);
  }, 0);

  const lines: string[] = [
    '<!-- Generated by scripts/generate-curriculum.ts — DO NOT EDIT BY HAND. -->',
    '<!-- Run `npm run gen:curriculum` after changing content/roadmap.json. -->',
    '',
    '# Curriculum',
    '',
    `**${lessons.length} ${pluralize(lessons.length, 'lesson')}** · roughly ${formatReadingTime(totalMinutes)} of reading ·`,
    'free and open source.',
    '',
    'Work top to bottom. Each lesson lists what it assumes you already know, so if',
    'you already have some of this, skip ahead — the prerequisites tell you whether',
    'you are ready.',
    '',
  ];

  for (const stage of roadmap.stages) {
    const stageNodes = ordered.filter((n) => n.stage === stage.id);

    const rows: string[] = [];
    for (const node of stageNodes) {
      const lesson = bySlug.get(node.id);
      if (!lesson) continue;
      const parsed = lessonSchema.safeParse(lesson.frontmatter);
      if (!parsed.success) continue;
      const { title, minutes, difficulty, summary, order } = parsed.data;
      rows.push(
        `| ${String(order).padStart(2, '0')} | [${title}](${lesson.file}) | ${minutes} min | ${difficulty} | ${summary} |`,
      );
    }
    if (rows.length === 0) continue;

    lines.push(`## Stage ${stage.id} · ${stage.name}`, '');
    lines.push('| # | Lesson | Time | Level | What it covers |');
    lines.push('|---|---|---|---|---|');
    lines.push(...rows);
    lines.push('');
  }

  lines.push(
    '---',
    '',
    'Prefer an interactive version with progress tracking and search?',
    'Visit <https://sumitsingh4411.github.io/ai-roadmap>.',
    '',
  );

  return lines.join('\n');
}

function main(): void {
  writeFileSync('CURRICULUM.md', renderCurriculum(readRoadmap(), readLessonFiles()), 'utf8');
  console.log('✓ Wrote CURRICULUM.md');
}

if (import.meta.url === `file://${process.argv[1]}`) main();
